name: Github jd_digital_floor bot

on:
    push:
        branches:
            - master
    schedule:
        - cron: '25 23 * * *'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
            - name: Run app
              run: npm install
            - run: node jd_digital_floor.js
              env:
                JD_COOKIE: ${{ secrets.JD_COOKIE }}
                PUSH_KEY: ${{ secrets.PUSH_KEY }}
